spring.application.name=jobtracker

#Conexão com o banco
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#Driver
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Configuração para nunca exibir a stack tracer na requisicao
spring.web.error.include-stacktrace=never